export const GETORDER = 'GETORDER';
export const GETORDERFAILED = 'GETORDERFAILED';
export const GETORDERSUCCESS = 'GETORDERSUCCESS';
export const CREATE_COMMAND = 'CREATE_COMMAND';
export const ADD_PRODUCT_TO_ORDER = 'ADD_PRODUCT_TO_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const PAY_ORDER = 'PAY_ORDER';
export const SEND_ALL_TO_KITCHEN = 'SEND_ALL_TO_KITCHEN';
export const RE_SEND_ALL_TO_KITCHEN = 'RE_SEND_ALL_TO_KITCHEN';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';
export const TRANSFER_ORDERS = 'TRANSFER_ORDERS';
export const CANCEL_PRODUCT_IN_ORDER = 'CANCEL_PRODUCT_IN_ORDER';
export const ADD_NOTE_TO_ORDER = 'ADD_NOTE_TO_ORDER';
export const SETUNIQUEIDOFDEVICE = 'SETUNIQUEIDOFDEVICE';

export const ADD_CONTACT_TO_ORDER = 'ADD_CONTACT_TO_ORDER';
export const ADD_CONTACT_TO_ORDER_SUCCESS = 'ADD_CONTACT_TO_ORDER_SUCCESS';
export const ADD_CONTACT_TO_ORDER_FAILED = 'ADD_CONTACT_TO_ORDER_FAILED';

export const TRANSFER_PRODUCT_TO_ORDER = 'TRANSFER_PRODUCT_TO_ORDER';
export const CHANGE_ORDER_CLASSIFYING_PRODUCT = 'CHANGE_ORDER_CLASSIFYING_PRODUCT';

export const BOOKING_ORDER_CREATION = "BOOKING_ORDER_CREATION";
export const UPDATE_UNIT_ORDER = "UPDATE_UNIT_ORDER";

export const GET_BOOKING_INFORMATION_TO_ORDER = "GET_BOOKING_INFORMATION_TO_ORDER";
export const GET_BOOKING_INFORMATION_TO_ORDER_SUCCESS = "GET_BOOKING_INFORMATION_TO_ORDER_SUCCESS";
export const GET_BOOKING_INFORMATION_TO_ORDER_FAILED = "GET_BOOKING_INFORMATION_TO_ORDER_FAILED";


export const CLOSE_ORDER = "CLOSE_ORDER";

export const GET_ALL_BOOKING_OF_DAY = "GET_ALL_BOOKING_OF_DAY";
export const GET_ALL_BOOKING_OF_DAY_SUCCESS = "GET_ALL_BOOKING_OF_DAY_SUCCESS";
export const GET_ALL_BOOKING_OF_DAY_FAILED = "GET_ALL_BOOKING_OF_DAY_FAILED";
export const ORDER_BEEN_SYNCED = "ORDER_BEEN_SYNCED";
export const ORDER_BEEN_SAVED = "ORDER_BEEN_SAVED";