export const GET_EMPLOYEE_STUFF = 'GET_EMPLOYEE_STUFF'
export const SET_EMPLOYEE_STUFF_SUCCUSS = 'SET_EMPLOYEE_STUFF_SUCCESS'
export const SET_EMPLOYEE_STUFF_FAILED = 'SET_EMPLOYEE_STUFF_FAILED'
export const SET_EMPLOYEE_ACTIVE_STUFF = 'SET_EMPLOYEE_ACTIVE_STUFF'